language: php
php:
  - '7.2'
  - '7.3'

global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
    
before_script: 
  - composer install
  - cp ./var/config/tests.php ./var/config/config.php
  - mkdir ./var/cache
  - mkdir ./var/logs
  - chmod -R 777 ./var/cache
  - chmod -R 777 ./var/logs
  - ./vendor/bin/phinx migrate
  - php ./App/Cli/bin/cli --generate-key --write
  
jobs:  
  include:
    - stage: "Lint"                # naming the Tests stage
      name: "PSR12"            # names the first Tests stage job
      script: ./vendor/bin/phpcs ./App --standard=PSR12 --colors -v
    - script: ./vendor/bin/phpcs ./App --standard=./rules.xml --colors -v
      name: "Custom Rules"     # names the second Tests stage job
    - stage: "PHP Stan"
      name: "PHP Stan"
      script: ./vendor/bin/phpstan analyse --level 0 ./App/
    - stage: "Tests"
      name: "Run Tests"
      script: ./vendor/bin/codecept run --steps
