language: php
php:
  - '7.2'
  - '7.3'

global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
    
before_script: 
  - composer install
  - cp ./var/config/tests.php ./var/config/config.php
  - mkdir ./var/cache
  - mkdir ./var/logs
  - chmod -R 777 ./var/cache
  - chmod -R 777 ./var/logs
  - ./vendor/bin/phinx migrate
  - php ./App/Cli/bin/cli --generate-key --write
script: 
  - ./vendor/bin/phpcs ./App --standard=PSR12 --colors -v
  - ./vendor/bin/phpcs ./App --standard=./rules.xml --colors -v
  - ./vendor/bin/phpstan analyse --level 0 ./App/
  - ./vendor/bin/codecept run --steps --coverage 
